### ISSUE TITLE
TestFlight & Adhoc iOS build incompatible

### ISSUE THREAD

**Issue by JasF** [pybee/rubicon#3] opened 2018-03-31 11:16 UTC
Cannot test it with TestFlight or AdHoc builds. Python crashes and returning -1. In simulator & debug builds work fine.

**Comment by freakboy3742** [comment] 2018-04-01 06:38
Duplicate of pybee/rubicon-objc#104. 

This repository is a stub for pointing at the language specific Rubicon bridges; if you find issues, please open them on the language specific repositories.

**Closed as completed by freakboy3742** 2018-04-01 06:38 UTC
